### ISSUE TITLE
360的壳失败log

### ISSUE THREAD

**Issue by CongCode** [WrBug/DeveloperHelper#16]
E/art: No implementation found for void com.wrbug.developerhelper.xposed.dumpdex.Native.dump(java.lang.String) (tried Java_com_wrbug_developerhelper_xposed_dumpdex_Native_dump and Java_com_wrbug_developerhelper_xposed_dumpdex_Native_dump__Ljava_lang_String_2)
 E/Xposed: java.lang.UnsatisfiedLinkError: No implementation found for void com.wrbug.developerhelper.xposed.dumpdex.Native.dump(java.lang.String) (tried Java_com_wrbug_developerhelper_xposed_dumpdex_Native_dump and Java_com_wrbug_developerhelper_xposed_dumpdex_Native_dump__Ljava_lang_String_2)
        at com.wrbug.developerhelper.xposed.dumpdex.Native.dump(Native Method)
        at com.wrbug.developerhelper.xposed.dumpdex.LowSdkDump.init(LowSdkDump.kt:37)
        at com.wrbug.developerhelper.xposed.dumpdex.Dump.init(Dump.kt:40)
        at com.wrbug.developerhelper.xposed.XposedInit.handleLoadPackage(XposedInit.kt:36)
        at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
        at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
        at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
        at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:153)
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
        at android.app.ActivityThread.handleBindApplication(<Xposed>)
        at android.app.ActivityThread.-wrap1(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1426)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5495)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by CongCode** [comment]
没load对so?

**Comment by CongCode** [comment]
..........
